### ISSUE TITLE
detailed PIN layout

### ISSUE THREAD

**Issue by nadavmisgav** [The6P4C/rp2040_ov2640#1]
Hi, i was wondering if you could provide the pin layout you used between the rp2040 and the ov2640 camera module.

**Comment by mihirbh2k** [comment]
yes pls I'm looking for the same maybe we can send our findings here and help each other or something.

**Comment by mihirbh2k** [comment]
This is what I have till now:-
SCL ----------------------------------- GPIO5 (1k pull up)
SDA-----------------------------------GPIO4 (1k pull up)
RESETB--------------------------------GPIO2
XCLK----------------------------------GPIO3
VSYNC--------------------------------GPIO16
D0-----------------------------------------GPIO6
D1--------------------------------------GPIO7
D2---------------------------------------GPIO8
D3---------------------------------------GPIO9
D4-----------------------------------------GPIO10
D5----------------------------------------GPIO11
D6----------------------------------------GPIO12
D7-------------------------------------GPIO13
PWDN---------------------not sure i dont think thsi library uses it
This does not work I'm pretty sure I'm making a stupid mistake or smth pls if anyone makes any progress

**Comment by nadavmisgav** [comment]
dont you have a PCLK and HREF connections? this is my connections where in my board XCLK is internally generated.

| Pico  | OV2640 | Notes                |
|-------|--------|----------------------|
| 3.3   | VCC    |                      |
| SCL   | GP5    | set pull up resistor |
| SDA   | GP4    | set pull up resistor |
| VSYNC | GP16   |                      |
| HREF  | GP15   |                      |
| PCLK  | GP14   |                      |
| D0    | GP6    |                      |
| RESET | GP2    |                      |
| GND   | GND    |                      |

**Comment by mihirbh2k** [comment]
Is this working? and did you change the PCLK and HREF in the pio file as well?

**Comment by chx123456nb** [comment]
Hello, guys, I'm just getting started with Raspberry PI, so what kind of pin maps are available?

**Comment by chx123456nb** [comment]
Hello, guys, I'm just getting started with Raspberry PI, so what kind of pin maps are available?

**Comment by nadavmisgav** [comment]
changed my board and added a pull up resistor to the vsync and it worked
